imports:
    - { resource: config_dev.yml }

doctrine:
    dbal:
        dbname:   "tweetr_test"
        user:     "tweetr_test"
        password: "tweetr_test"

framework:
    test: ~
    session:
        #storage_id: session.storage.mock_file
        storage_id: session.storage.filesystem
    profiler:
        collect: false


web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

liip_functional_test: ~
