parameters:
    lennaert.tweet.controller.class: Finalist\LennaertBundle\Controller\TweetController

services:
    lennaert.tweet.controller:
        class: %lennaert.tweet.controller.class%A
        arguments: [@templating, @form.factory, @llvdl_tweeter_core.tweet_service]