parameters:
#    lennaert.example.class: Finalist\LennaertBundle\Example

services:
#    lennaert.example:
#        class: %lennaert.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
