parameters:
    finalist_tweeter_core.tweeter_service.class: Finalist\TweeterCoreBundle\Service\TweetService
    finalist_tweeter_core.tweet_repository.class: Finalist\TweeterCoreBundle\Repository\Impl\TweetRepositoryDoctrineImpl
    finalist_tweeter_core.tweeter_repository.class: Finalist\TweeterCoreBundle\Repository\Impl\TweeterRepositoryDoctrineImpl

services:
    finalist_tweeter_core.tweeter_repository:
        class: %finalist_tweeter_core.tweeter_repository.class%
        arguments: [@doctrine.orm.entity_manager]
        public: false
    finalist_tweeter_core.tweet_repository:
        class: %finalist_tweeter_core.tweet_repository.class%
        arguments: [@doctrine.orm.entity_manager]
        public: false

    finalist_tweeter_core.tweet_service:
        class: %finalist_tweeter_core.tweeter_service.class%
        arguments: [@finalist_tweeter_core.tweet_repository, @finalist_tweeter_core.tweeter_repository]

